#!/bin/bash

# Check secureboot.d/how-to-contribute-to-secureboot.d.md on how this script works
# and how to contribute with other vendors

# Environment variables:
#
# SHIM_FULLPATH_BINARY
# GRUB_FULLPATH_BINARY
# SHIM_FULLPATH_SOURCE_CODE_TAR_GZ
# GRUB_FULLPATH_SOURCE_CODE_TAR_GZ

# Definitions
SB_VENDOR="ubuntu"
SB_EFI_PLATFORM="x64"
CURRENT_DIRECTORY="$(pwd)"
DOWNLOAD_TMP_DIR="${CURRENT_DIRECTORY}-${SB_VENDOR}-${SB_EFI_PLATFORM}-tmp"

if [ ! -d "${DOWNLOAD_TMP_DIR}" ] ; then
  mkdir "${DOWNLOAD_TMP_DIR}"
fi

# Signed SHIM Binary download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'shim-download'
cd 'shim-download'
wget -q 'http://de.archive.ubuntu.com/ubuntu/pool/main/s/shim-signed/shim-signed_1.51+15.4-0ubuntu9_amd64.deb'
dpkg-deb -x shim-signed_1.51+15.4-0ubuntu9_amd64.deb ./

# Signed SHIM Binary final copy
cp usr/lib/shim/shim${SB_EFI_PLATFORM}.efi.signed ${SHIM_FULLPATH_BINARY}

# Signed GRUB Binary download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'grub-download'
cd 'grub-download'
wget -q 'http://de.archive.ubuntu.com/ubuntu/pool/main/g/grub2-signed/grub-efi-amd64-signed_1.182~22.04.1+2.06-2ubuntu10_amd64.deb'
dpkg-deb -x grub-efi-amd64-signed_1.182~22.04.1+2.06-2ubuntu10_amd64.deb ./

# Signed GRUB Binary final copy
cp usr/lib/grub/x86_64-efi-signed/grub${SB_EFI_PLATFORM}.efi.signed ${GRUB_FULLPATH_BINARY}

# Signed SHIM Source code download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'shim-src-download'
cd 'shim-src-download'
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/s/shim-signed/shim-signed_1.51.tar.xz'
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/s/shim-signed/shim-signed_1.51.dsc'

wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/s/shim/shim_15.4-0ubuntu9.debian.tar.xz'
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/s/shim/shim_15.4-0ubuntu9.dsc'

wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/s/shim/shim_15.4.orig.tar.bz2'

# Signed SHIM Source code final copy
cd ${DOWNLOAD_TMP_DIR}
tar czf "${SB_VENDOR}-${SB_EFI_PLATFORM}-shim-sourcecode.tar.gz" 'shim-src-download'
cp "${SB_VENDOR}-${SB_EFI_PLATFORM}-shim-sourcecode.tar.gz" "${SHIM_FULLPATH_SOURCE_CODE_TAR_GZ}"

# Signed GRUB Source code download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'grub-src-download'
cd 'grub-src-download'

wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/g/grub2-signed/grub2-signed_1.182~22.04.1.tar.xz'
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/g/grub2-signed/grub2-signed_1.182~22.04.1.dsc'

wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/g/grub2/grub2_2.06-2ubuntu7.debian.tar.xz'
wget -q 'http://archive.ubuntu.com/ubuntu/pool/main/g/grub2/grub2_2.06-2ubuntu7.dsc'

wget -q 'hhttp://archive.ubuntu.com/ubuntu/pool/main/g/grub2/grub2_2.06.orig.tar.xz'

# Signed GRUB Source code final copy
cd ${DOWNLOAD_TMP_DIR}
tar czf "${SB_VENDOR}-${SB_EFI_PLATFORM}-grub-sourcecode.tar.gz" 'grub-src-download'
cp "${SB_VENDOR}-${SB_EFI_PLATFORM}-grub-sourcecode.tar.gz" "${GRUB_FULLPATH_SOURCE_CODE_TAR_GZ}"

# Make sure to download temporary directory
rm -rf ${DOWNLOAD_TMP_DIR}

# Make sure to come back to the original directory
cd ${CURRENT_DIRECTORY}
