#!/bin/bash

# Check secureboot.d/how-to-contribute-to-secureboot.d.md on how this script works
# and how to contribute with other vendors

# Environment variables:
#
# SHIM_FULLPATH_BINARY
# GRUB_FULLPATH_BINARY
# SHIM_FULLPATH_SOURCE_CODE_TAR_GZ
# GRUB_FULLPATH_SOURCE_CODE_TAR_GZ

DOWNLOAD_RETURN_STATUS=0

# Definitions
SB_VENDOR="debian"
SB_EFI_PLATFORM="x64"
CURRENT_DIRECTORY="$(pwd)"
DOWNLOAD_TMP_DIR="${CURRENT_DIRECTORY}-${SB_VENDOR}-${SB_EFI_PLATFORM}-tmp"

if [ ! -d "${DOWNLOAD_TMP_DIR}" ] ; then
  mkdir "${DOWNLOAD_TMP_DIR}"
fi

# Signed SHIM Binary download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'shim-download'
cd 'shim-download'
wget -q 'https://snapshot.debian.org/archive/debian/20210713T032850Z/pool/main/s/shim-signed/shim-signed_1.38%2B15.4-7_amd64.deb' || DOWNLOAD_RETURN_STATUS=1
dpkg-deb -x shim-signed_1.38+15.4-7_amd64.deb ./

# Signed SHIM Binary final copy
cp usr/lib/shim/shimx64.efi.signed ${SHIM_FULLPATH_BINARY}

# Signed GRUB Binary download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'grub-download'
cd 'grub-download'
wget -q 'https://snapshot.debian.org/archive/debian/20220814T034728Z/pool/main/g/grub-efi-amd64-signed/grub-efi-amd64-signed_1%2B2.06%2B3~deb11u1_amd64.deb' || DOWNLOAD_RETURN_STATUS=1
dpkg-deb -x grub-efi-amd64-signed_1+2.06+3~deb11u1_amd64.deb ./

# Signed GRUB Binary final copy
cp usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed ${GRUB_FULLPATH_BINARY}

# Signed SHIM Source code download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'shim-src-download'
cd 'shim-src-download'
wget -q 'https://snapshot.debian.org/archive/debian/20210713T032850Z/pool/main/s/shim-signed/shim-signed_1.38.tar.xz' || DOWNLOAD_RETURN_STATUS=1
wget -q 'https://snapshot.debian.org/archive/debian/20210713T032850Z/pool/main/s/shim-signed/shim-signed_1.38.dsc' || DOWNLOAD_RETURN_STATUS=1

wget -q 'https://snapshot.debian.org/archive/debian/20210712T151030Z/pool/main/s/shim/shim_15.4-7.debian.tar.xz' || DOWNLOAD_RETURN_STATUS=1
wget -q 'https://snapshot.debian.org/archive/debian/20210712T151030Z/pool/main/s/shim/shim_15.4-7.dsc' || DOWNLOAD_RETURN_STATUS=1

wget -q 'https://snapshot.debian.org/archive/debian/20210712T204518Z/pool/main/s/shim/shim_15.4-7~deb10u1.debian.tar.xz' || DOWNLOAD_RETURN_STATUS=1
wget -q 'https://snapshot.debian.org/archive/debian/20210712T204518Z/pool/main/s/shim/shim_15.4-7~deb10u1.dsc' || DOWNLOAD_RETURN_STATUS=1

wget -q 'https://snapshot.debian.org/archive/debian/20210417T203747Z/pool/main/s/shim/shim_15.4.orig.tar.bz2' || DOWNLOAD_RETURN_STATUS=1

# Signed SHIM Source code final copy
cd ${DOWNLOAD_TMP_DIR}
tar czf "${SB_VENDOR}-${SB_EFI_PLATFORM}-shim-sourcecode.tar.gz" 'shim-src-download'
cp "${SB_VENDOR}-${SB_EFI_PLATFORM}-shim-sourcecode.tar.gz" "${SHIM_FULLPATH_SOURCE_CODE_TAR_GZ}"

# Signed GRUB Source code download
cd ${DOWNLOAD_TMP_DIR}
mkdir 'grub-src-download'
cd 'grub-src-download'

wget -q 'https://snapshot.debian.org/archive/debian/20220813T214310Z/pool/main/g/grub-efi-amd64-signed/grub-efi-amd64-signed_1%2B2.06%2B3~deb11u1.tar.xz' || DOWNLOAD_RETURN_STATUS=1
wget -q 'https://snapshot.debian.org/archive/debian/20220813T214310Z/pool/main/g/grub-efi-amd64-signed/grub-efi-amd64-signed_1%2B2.06%2B3~deb11u1.dsc' || DOWNLOAD_RETURN_STATUS=1

wget -q 'https://snapshot.debian.org/archive/debian/20220807T030023Z/pool/main/g/grub2/grub2_2.06-3~deb11u1.debian.tar.xz' || DOWNLOAD_RETURN_STATUS=1
wget -q 'https://snapshot.debian.org/archive/debian/20220807T030023Z/pool/main/g/grub2/grub2_2.06-3~deb11u1.dsc' || DOWNLOAD_RETURN_STATUS=1

wget -q 'https://snapshot.debian.org/archive/debian/20211128T160803Z/pool/main/g/grub2/grub2_2.06.orig.tar.xz' || DOWNLOAD_RETURN_STATUS=1

# Signed GRUB Source code final copy
cd ${DOWNLOAD_TMP_DIR}
tar czf "${SB_VENDOR}-${SB_EFI_PLATFORM}-grub-sourcecode.tar.gz" 'grub-src-download'
cp "${SB_VENDOR}-${SB_EFI_PLATFORM}-grub-sourcecode.tar.gz" "${GRUB_FULLPATH_SOURCE_CODE_TAR_GZ}"

# Make sure to download temporary directory
rm -rf ${DOWNLOAD_TMP_DIR}

# Make sure to come back to the original directory
cd ${CURRENT_DIRECTORY}

exit ${DOWNLOAD_RETURN_STATUS}
